import Core
import Foundation

public struct ResetPasswordRequest: GoogleCloudModel {
    /// An out-of-band (OOB) code generated by accounts.sendOobCode request
    public let oobCode: String?
    /// The new password to be set for this account
    public let newPassword: String?
    /// The current password of the account to be modified
    public let oldPassword: String?
    /// The email of the account to be modified
    public let email: String?
    /// The tenant ID of the Identity Platform tenant
    public let tenantId: String?
    
    public init(
        oobCode: String? = nil,
        newPassword: String? = nil,
        oldPassword: String? = nil,
        email: String? = nil,
        tenantId: String? = nil
    ) {
        self.oobCode = oobCode
        self.newPassword = newPassword
        self.oldPassword = oldPassword
        self.email = email
        self.tenantId = tenantId
    }
} 