import Core
import Foundation

public struct SignInWithGameCenterRequest: GoogleCloudModel {
    /// Required. The user's Game Center player ID (Deprecated by Apple)
    public let playerId: String
    /// Required. The URL to fetch the Apple public key
    public let publicKeyUrl: String
    /// Required. The verification signature data generated by Apple
    public let signature: String
    /// Required. A random string used to generate the signature
    public let salt: String
    /// Required. The time when the signature was created by Apple
    public let timestamp: String
    /// A valid ID token for linking Game Center to an existing account
    public let idToken: String?
    /// The user's Game Center display name
    public let displayName: String?
    /// The ID of the Identity Platform tenant
    public let tenantId: String?
    /// The user's Game Center team player ID
    public let teamPlayerId: String?
    /// The user's Game Center game player ID
    public let gamePlayerId: String?
    
    public init(
        playerId: String,
        publicKeyUrl: String,
        signature: String,
        salt: String,
        timestamp: String,
        idToken: String? = nil,
        displayName: String? = nil,
        tenantId: String? = nil,
        teamPlayerId: String? = nil,
        gamePlayerId: String? = nil
    ) {
        self.playerId = playerId
        self.publicKeyUrl = publicKeyUrl
        self.signature = signature
        self.salt = salt
        self.timestamp = timestamp
        self.idToken = idToken
        self.displayName = displayName
        self.tenantId = tenantId
        self.teamPlayerId = teamPlayerId
        self.gamePlayerId = gamePlayerId
    }
} 